<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-76c922
Date:    2018-10-28 12:56:40
Version: v2.1.4
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-76c922",
    "email": {
        "to": "",
        "cc": "",
        "bcc": "",
        "subject": "",
        "template": ""
    },
    "admin": {
        "users": "admin:10d57",
        "dataDelivery": "fileOnly"
    },
    "thankyou": {
        "url": "http:\/\/www.app-ear.com.ar",
        "message": "Gracias por el env\u00edo de los datos! Un experto se contactar\u00e1 con usted por email para realizar la validaci\u00f3n de los mismos!",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [
        {
            "disabled": false,
            "action": "show",
            "selector": "f9",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "montana"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f10",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "llanura"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f11",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "estuario"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f12",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "laguna"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f10,f11,f12",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "montana"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f9,f11,f12",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "llanura"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f9,f10,f12",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "estuario"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f9,f10,f11",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "laguna"
                }
            ]
        }
    ],
    "fields": [
        {
            "label": "Page Navigation",
            "field_type": "page_navigation",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "navigation": {
                    "style": "steps",
                    "showNumber": true,
                    "isButtonPrev": false,
                    "titles": [
                        {
                            "id": "f4",
                            "title": "Inicio"
                        },
                        {
                            "id": "f9",
                            "title": "R\u00edo de monta\u00f1a"
                        },
                        {
                            "id": "f10",
                            "title": "R\u00edo de llanura"
                        },
                        {
                            "id": "f11",
                            "title": "Estuario o playa"
                        },
                        {
                            "id": "f12",
                            "title": "Laguna"
                        },
                        {
                            "id": "f73",
                            "title": "Fotos"
                        },
                        {
                            "id": "f0",
                            "title": "Enviar"
                        }
                    ]
                }
            },
            "id": "f5",
            "cid": "c31"
        },
        {
            "label": "Tu email: (para que te contacte un revisor)",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f6",
            "cid": "c37"
        },
        {
            "label": "\u00bfEn que fecha visitaste el lugar?",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "date": {
                    "format": "mm\/dd\/yyyy"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f7",
            "cid": "c42"
        },
        {
            "label": "\u00bfQu\u00e9 tipo de ambiente es?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "R\u00edo de monta\u00f1a",
                        "checked": false,
                        "value": "montana"
                    },
                    {
                        "label": "R\u00edo de llanura",
                        "checked": false,
                        "value": "llanura"
                    },
                    {
                        "label": "Estuario o playa",
                        "checked": false,
                        "value": "estuario"
                    },
                    {
                        "label": "Laguna",
                        "checked": null,
                        "value": "laguna"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f8",
            "cid": "c47"
        },
        {
            "label": "Inicio",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "Inicio",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                }
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "Secci\u00f3n de R\u00edos de Monta\u00f1a",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "id": "f41",
            "cid": "c265"
        },
        {
            "label": "1.\tLa zona cercana al sitio del arroyo, \u00bfpara qu\u00e9 se usa mayormente?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Es una zona industrial o minera",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "Es una zona residencial muy urbana",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Es una zona residencial suburbana",
                        "checked": false,
                        "value": "4"
                    },
                    {
                        "label": "Es una zona agropecuaria",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "Es una reserva, o una zona muy natural",
                        "checked": null,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f14",
            "cid": "c85"
        },
        {
            "label": "\u00bfHay ganado cerca del arroyo?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay un feedlot cerca",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "Si, hay abundante y disperso",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Si, pero poco",
                        "checked": false,
                        "value": "4"
                    },
                    {
                        "label": "No, no hay ganado",
                        "checked": null,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f16",
            "cid": "c96"
        },
        {
            "label": "\u00bfC\u00f3mo es la vegetaci\u00f3n de ribera?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Hay s\u00f3lo plantas aut\u00f3ctonas",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Hay  \u00e1rboles introducidos, ca\u00f1a o acacia negra",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "Sin \u00e1rboles o con poca agricultura",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f17",
            "cid": "c101"
        },
        {
            "label": "\u00bfHay plantas acu\u00e1ticas?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay sumergidas en el agua y tambi\u00e9n en las m\u00e1rgenes",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Si, hay sumergidas en el agua, pero no hay en las m\u00e1rgenes",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, de ning\u00fan tipo",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f18",
            "cid": "c106"
        },
        {
            "label": "\u00bfEs transparente el agua?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Es transparente",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Es marr\u00f3n",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Es oscura",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f19",
            "cid": "c111"
        },
        {
            "label": "\u00bfTiene mal olor el agua?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Huele bien",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Huele mal",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f20",
            "cid": "c120"
        },
        {
            "label": "\u00bfHay basura en la ribera?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Sin basura",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Presente pero no abundante",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "Abundante",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No se",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f21",
            "cid": "c125"
        },
        {
            "label": "\u00bfC\u00f3mo es la corriente?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "R\u00e1pida",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Lenta",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f22",
            "cid": "c130"
        },
        {
            "label": "\u00bfEsta desbordado el r\u00edo? O en su cauce?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Desbordado",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "En su cauce",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f23",
            "cid": "c135"
        },
        {
            "label": "\u00bfEst\u00e1 canalizado o entubado?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Esta canalizado o entubado",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No est\u00e1 canalizado ni entubado ",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f24",
            "cid": "c140"
        },
        {
            "label": "El fondo del arroyo tiene:",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Arcilla\/Barro",
                        "checked": false,
                        "value": "+2.5"
                    },
                    {
                        "label": "Arena gruesa",
                        "checked": false,
                        "value": "+2.5"
                    },
                    {
                        "label": "Piedras o grava",
                        "checked": false,
                        "value": "+2.5"
                    },
                    {
                        "label": "Guijarros ",
                        "checked": null,
                        "value": "+2.5"
                    },
                    {
                        "label": "Es artificial (cemento)",
                        "checked": null,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": ""
            },
            "id": "f26",
            "cid": "c150"
        },
        {
            "label": "\u00bfC\u00f3mo es la pendiente de las m\u00e1rgenes?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Muy pronunciada! (>45\u00ba)",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No muy pronuciada (<45\u00ba)",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f27",
            "cid": "c155"
        },
        {
            "label": "\u00bfEsta sombreado el arroyo?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, totalmente cubierto",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Si, un poco",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No est\u00e1 sombreado",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f28",
            "cid": "c160"
        },
        {
            "label": "R\u00edo de monta\u00f1a",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "R\u00edo de monta\u00f1a",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                },
                "hidden": true
            },
            "id": "f9",
            "cid": "c53"
        },
        {
            "label": "Secci\u00f3n de R\u00edos de Llanura",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "cid": "c277",
            "id": "f43"
        },
        {
            "label": "La zona cercana al sitio del arroyo, \u00bfpara qu\u00e9 se usa mayormente?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Es una zona industrial o minera",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "Es una zona residencial muy urbana",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Es una zona residencial suburbana",
                        "checked": false,
                        "value": "4"
                    },
                    {
                        "label": "Es una zona agropecuaria",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "Es una reserva, o una zona muy natural",
                        "checked": null,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c174",
            "id": "f29"
        },
        {
            "label": "\u00bfHay ganado cerca del arroyo?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay un feedlot cerca",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "Si, hay abundante y disperso",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Si, pero poco",
                        "checked": false,
                        "value": "4"
                    },
                    {
                        "label": "No, no hay ganado",
                        "checked": null,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c180",
            "id": "f30"
        },
        {
            "label": "\u00bfC\u00f3mo es la vegetaci\u00f3n de ribera?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Hay s\u00f3lo plantas aut\u00f3ctonas",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Hay  \u00e1rboles introducidos, ca\u00f1a o acacia negra",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "Sin \u00e1rboles o con poca agricultura",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c186",
            "id": "f31"
        },
        {
            "label": "\u00bfHay plantas acu\u00e1ticas?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay sumergidas en el agua y tambi\u00e9n en las m\u00e1rgenes",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Si, hay sumergidas en el agua, pero no hay en las m\u00e1rgenes",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, de ning\u00fan tipo",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c192",
            "id": "f32"
        },
        {
            "label": "\u00bfEs transparente el agua?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Es transparente",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Es marr\u00f3n",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Es oscura",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c198",
            "id": "f33"
        },
        {
            "label": "\u00bfTiene mal olor el agua?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Huele bien",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Huele mal",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c204",
            "id": "f34"
        },
        {
            "label": "\u00bfHay basura en la ribera?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Sin basura",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Presente pero no abundante",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "Abundante",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No se",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c210",
            "id": "f35"
        },
        {
            "label": "\u00bfC\u00f3mo es la corriente?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "R\u00e1pida",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Lenta",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c216",
            "id": "f36"
        },
        {
            "label": "\u00bfEsta desbordado el r\u00edo? O en su cauce?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Desbordado",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "En su cauce",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c222",
            "id": "f37"
        },
        {
            "label": "\u00bfEst\u00e1 canalizado o entubado?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Esta canalizado o entubado",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No est\u00e1 canalizado ni entubado ",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c228",
            "id": "f38"
        },
        {
            "label": "El fondo del arroyo tiene:",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Arcilla\/Barro",
                        "checked": false,
                        "value": "+2.5"
                    },
                    {
                        "label": "Arena gruesa",
                        "checked": false,
                        "value": "+2.5"
                    },
                    {
                        "label": "Piedras o grava",
                        "checked": false,
                        "value": "+2.5"
                    },
                    {
                        "label": "Guijarros ",
                        "checked": null,
                        "value": "+2.5"
                    },
                    {
                        "label": "Es artificial (cemento)",
                        "checked": null,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": ""
            },
            "cid": "c234",
            "id": "f39"
        },
        {
            "label": "\u00bfC\u00f3mo es la pendiente de las m\u00e1rgenes?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Muy pronunciada! (>45\u00ba)",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No muy pronuciada (<45\u00ba)",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c240",
            "id": "f40"
        },
        {
            "label": "R\u00edo de llanura",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "R\u00edo de llanura",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                },
                "hidden": true
            },
            "id": "f10",
            "cid": "c58"
        },
        {
            "label": "Secci\u00f3n de Estuarios y playas",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "cid": "c270",
            "id": "f42"
        },
        {
            "label": "La zona cercana al sitio del sitio, \u00bfpara qu\u00e9 se usa mayormente?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Es una zona industrial o minera",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "Es una zona residencial muy urbana",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Es una zona residencial suburbana",
                        "checked": false,
                        "value": "4"
                    },
                    {
                        "label": "Es una zona agropecuaria",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "Es una reserva, o una zona muy natural",
                        "checked": null,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c294",
            "id": "f45"
        },
        {
            "label": "\u00bfHay ganado cerca del sitio?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay un feedlot cerca",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "Si, hay abundante y disperso",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Si, pero poco",
                        "checked": false,
                        "value": "4"
                    },
                    {
                        "label": "No, no hay ganado",
                        "checked": null,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c301",
            "id": "f46"
        },
        {
            "label": "\u00bfC\u00f3mo es la vegetaci\u00f3n de ribera?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Hay s\u00f3lo plantas aut\u00f3ctonas",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Hay  \u00e1rboles introducidos, ca\u00f1a o acacia negra",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "Sin \u00e1rboles o con poca agricultura",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c308",
            "id": "f47"
        },
        {
            "label": "\u00bfHay plantas acu\u00e1ticas?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay sumergidas en el agua y tambi\u00e9n en las m\u00e1rgenes",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Si, hay sumergidas en el agua, pero no hay en las m\u00e1rgenes",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, de ning\u00fan tipo",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c316",
            "id": "f48"
        },
        {
            "label": "\u00bfEs transparente el agua?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Es transparente",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Es marr\u00f3n",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Es oscura",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c323",
            "id": "f49"
        },
        {
            "label": "\u00bfTiene mal olor el agua?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Huele bien",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Huele mal",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c330",
            "id": "f50"
        },
        {
            "label": "\u00bfHay basura en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Sin basura",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Presente pero no abundante",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "Abundante",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No se",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c337",
            "id": "f51"
        },
        {
            "label": "\u00bfHay juncales en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si hay juncales",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Si aislados",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, no hay juncales",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f52",
            "cid": "c351"
        },
        {
            "label": "\u00bfHay pajonales en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si hay pajonales",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Si aislados",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, no hay pajonaes",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f53",
            "cid": "c356"
        },
        {
            "label": "\u00bfHay \u00e1rboles en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, abundantes",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No, no hay \u00e1rboles",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f54",
            "cid": "c361"
        },
        {
            "label": "\u00bfHay murallas en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay una muralla a lo largo de la costa",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No, no hay una muralla",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f55",
            "cid": "c366"
        },
        {
            "label": "\u00bfHay muelles o escolleras cerca?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay muelles",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, no hay nada",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f56",
            "cid": "c371"
        },
        {
            "label": "\u00bfHay edificaciones temporarias?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay algunas casillas o campings",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, no hay nada",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f57",
            "cid": "c376"
        },
        {
            "label": "\u00bfHay escombros en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay escombros por toda la costa",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No, no hay escombros",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f58",
            "cid": "c381"
        },
        {
            "label": "Estuario o playa",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "Estuario o playa",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                },
                "hidden": true
            },
            "id": "f11",
            "cid": "c63"
        },
        {
            "label": "Secci\u00f3n de Lagunas",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "cid": "c283",
            "id": "f44"
        },
        {
            "label": "La zona cercana al sitio, \u00bfpara qu\u00e9 se usa mayormente?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Es una zona industrial o minera",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "Es una zona residencial muy urbana",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Es una zona residencial suburbana",
                        "checked": false,
                        "value": "4"
                    },
                    {
                        "label": "Es una zona agropecuaria",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "Es una reserva, o una zona muy natural",
                        "checked": null,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c391",
            "id": "f59"
        },
        {
            "label": "\u00bfHay ganado cerca del lugar?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay un feedlot cerca",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "Si, hay abundante y disperso",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Si, pero poco",
                        "checked": false,
                        "value": "4"
                    },
                    {
                        "label": "No, no hay ganado",
                        "checked": null,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c397",
            "id": "f60"
        },
        {
            "label": "\u00bfC\u00f3mo es la vegetaci\u00f3n de ribera?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Hay s\u00f3lo plantas aut\u00f3ctonas",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Hay  \u00e1rboles introducidos, ca\u00f1a o acacia negra",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "Sin \u00e1rboles o con poca agricultura",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c403",
            "id": "f61"
        },
        {
            "label": "\u00bfHay plantas acu\u00e1ticas?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay sumergidas en el agua y tambi\u00e9n en las m\u00e1rgenes",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Si, hay sumergidas en el agua, pero no hay en las m\u00e1rgenes",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, de ning\u00fan tipo",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c409",
            "id": "f62"
        },
        {
            "label": "\u00bfEs transparente el agua?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Es transparente",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Es marr\u00f3n",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Es oscura",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c415",
            "id": "f63"
        },
        {
            "label": "\u00bfTiene mal olor el agua?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Huele bien",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Huele mal",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c421",
            "id": "f64"
        },
        {
            "label": "\u00bfHay basura en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Sin basura",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Presente pero no abundante",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "Abundante",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No se",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c427",
            "id": "f65"
        },
        {
            "label": "\u00bfHay juncales en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si hay juncales",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "Si aislados",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, no hay juncales",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": null,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c440",
            "id": "f66"
        },
        {
            "label": "\u00bfHay murallas en la costa?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay una muralla a lo largo de la costa",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "No, no hay una muralla",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c446",
            "id": "f67"
        },
        {
            "label": "\u00bfHay muelles o escolleras cerca?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay muelles",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, no hay nada",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c452",
            "id": "f68"
        },
        {
            "label": "\u00bfHay edificaciones temporarias?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Si, hay algunas casillas o campings",
                        "checked": false,
                        "value": "5"
                    },
                    {
                        "label": "No, no hay nada",
                        "checked": false,
                        "value": "10"
                    },
                    {
                        "label": "No lo s\u00e9",
                        "checked": false,
                        "value": "NS"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c458",
            "id": "f69"
        },
        {
            "label": "Laguna",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "Laguna",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                },
                "hidden": true
            },
            "id": "f12",
            "cid": "c68"
        },
        {
            "label": "Adjunta tus fotos del lugar (entre 1 y 4 fotos)",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "jpg"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "multiple": true
            },
            "id": "f74",
            "cid": "c490"
        },
        {
            "label": "Fotos",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "Fotos",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                }
            },
            "id": "f73",
            "cid": "c485"
        },
        {
            "label": "\u00bfViste alguno de los siguientes?",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Ranas",
                        "checked": false
                    },
                    {
                        "label": "Tortugas",
                        "checked": false
                    },
                    {
                        "label": "Peces",
                        "checked": false
                    },
                    {
                        "label": "Mosquitos",
                        "checked": null
                    },
                    {
                        "label": "Lib\u00e9lulas",
                        "checked": null
                    },
                    {
                        "label": "Serpientes",
                        "checked": null
                    },
                    {
                        "label": "Mam\u00edferos",
                        "checked": null
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": ""
            },
            "id": "f71",
            "cid": "c475"
        },
        {
            "label": "\u00bfQuieres enviarnos alguna nota?",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f72",
            "cid": "c480"
        },
        {
            "label": "Google reCaptcha",
            "field_type": "recaptcha",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "hidden": false
            },
            "labelHide": true,
            "recaptcha": {
                "theme": "light",
                "siteKey": "6LfwPHcUAAAAAGct6jGIrSslcNiLoWGUWNy3URxx",
                "secretKey": "6LfwPHcUAAAAAISPFFLU0O2l4hLUyzObmXChE",
                "language": "",
                "errMsg": "Google reCaptcha validation error. Please try again.",
                "maxFailed": 3
            },
            "id": "f75",
            "cid": "c505"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Enviar",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "Enviar",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "no"
    },
    "licenseKey": "",
    "lang": {
        "language": "es"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class