package ilpla.appear;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class utilidades {
private static utilidades mostCurrent = new utilidades();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public anywheresoftware.b4a.samples.httputils2.httputils2service _httputils2service = null;
public ilpla.appear.main _main = null;
public ilpla.appear.frmprincipal _frmprincipal = null;
public ilpla.appear.frmevaluacion _frmevaluacion = null;
public ilpla.appear.game_ciclo _game_ciclo = null;
public ilpla.appear.game_sourcepoint _game_sourcepoint = null;
public ilpla.appear.game_comunidades _game_comunidades = null;
public ilpla.appear.game_trofica _game_trofica = null;
public ilpla.appear.aprender_tipoagua _aprender_tipoagua = null;
public ilpla.appear.frmaprender _frmaprender = null;
public ilpla.appear.frmresultados _frmresultados = null;
public ilpla.appear.frmhabitatestuario _frmhabitatestuario = null;
public ilpla.appear.game_ahorcado _game_ahorcado = null;
public ilpla.appear.aprender_factores _aprender_factores = null;
public ilpla.appear.frmminigames _frmminigames = null;
public ilpla.appear.frmhabitatrio _frmhabitatrio = null;
public ilpla.appear.frmabout _frmabout = null;
public ilpla.appear.frmhabitatlaguna _frmhabitatlaguna = null;
public ilpla.appear.frmperfil _frmperfil = null;
public ilpla.appear.envioarchivos _envioarchivos = null;
public ilpla.appear.frmcamara _frmcamara = null;
public ilpla.appear.register _register = null;
public ilpla.appear.frmlocalizacion _frmlocalizacion = null;
public ilpla.appear.frmtiporio _frmtiporio = null;
public ilpla.appear.game_memory _game_memory = null;
public static String  _mensaje(anywheresoftware.b4a.BA _ba,String _titulo,String _text,String _botontextoyes,String _botontextocan,String _botontextono) throws Exception{
flm.b4a.betterdialogs.BetterDialogs _dial = null;
anywheresoftware.b4a.objects.ImageViewWrapper _msgbottomimg = null;
anywheresoftware.b4a.objects.PanelWrapper _panelcontent = null;
anywheresoftware.b4a.objects.LabelWrapper _titulolbl = null;
anywheresoftware.b4a.objects.ImageViewWrapper _msgtopimg = null;
anywheresoftware.b4a.objects.LabelWrapper _contenido = null;
String _msg = "";
 //BA.debugLineNum = 44;BA.debugLine="Sub Mensaje (titulo As String, text As String, bot";
 //BA.debugLineNum = 45;BA.debugLine="Dim dial As BetterDialogs";
_dial = new flm.b4a.betterdialogs.BetterDialogs();
 //BA.debugLineNum = 46;BA.debugLine="Dim MsgBottomImg As ImageView";
_msgbottomimg = new anywheresoftware.b4a.objects.ImageViewWrapper();
 //BA.debugLineNum = 47;BA.debugLine="Dim panelcontent As Panel";
_panelcontent = new anywheresoftware.b4a.objects.PanelWrapper();
 //BA.debugLineNum = 48;BA.debugLine="Dim titulolbl As Label";
_titulolbl = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 49;BA.debugLine="Dim MsgTopImg As ImageView";
_msgtopimg = new anywheresoftware.b4a.objects.ImageViewWrapper();
 //BA.debugLineNum = 50;BA.debugLine="Dim contenido As Label";
_contenido = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 51;BA.debugLine="Dim msg As String";
_msg = "";
 //BA.debugLineNum = 53;BA.debugLine="MsgBottomImg.Initialize(\"\")";
_msgbottomimg.Initialize(_ba,"");
 //BA.debugLineNum = 54;BA.debugLine="MsgTopImg.Initialize(\"\")";
_msgtopimg.Initialize(_ba,"");
 //BA.debugLineNum = 55;BA.debugLine="panelcontent.Initialize(\"\")";
_panelcontent.Initialize(_ba,"");
 //BA.debugLineNum = 56;BA.debugLine="titulolbl.Initialize(\"\")";
_titulolbl.Initialize(_ba,"");
 //BA.debugLineNum = 57;BA.debugLine="contenido.Initialize(\"\")";
_contenido.Initialize(_ba,"");
 //BA.debugLineNum = 59;BA.debugLine="MsgBottomImg.Bitmap = LoadBitmap(File.DirAssets,";
_msgbottomimg.setBitmap((android.graphics.Bitmap)(anywheresoftware.b4a.keywords.Common.LoadBitmap(anywheresoftware.b4a.keywords.Common.File.getDirAssets(),"MsgBottom.png").getObject()));
 //BA.debugLineNum = 60;BA.debugLine="MsgTopImg.Bitmap = LoadBitmap(File.DirAssets, \"Ms";
_msgtopimg.setBitmap((android.graphics.Bitmap)(anywheresoftware.b4a.keywords.Common.LoadBitmap(anywheresoftware.b4a.keywords.Common.File.getDirAssets(),"MsgTop.png").getObject()));
 //BA.debugLineNum = 61;BA.debugLine="MsgTopImg.Gravity = Gravity.FILL";
_msgtopimg.setGravity(anywheresoftware.b4a.keywords.Common.Gravity.FILL);
 //BA.debugLineNum = 62;BA.debugLine="MsgBottomImg.Gravity = Gravity.FILL";
_msgbottomimg.setGravity(anywheresoftware.b4a.keywords.Common.Gravity.FILL);
 //BA.debugLineNum = 64;BA.debugLine="titulolbl.Text = titulo";
_titulolbl.setText((Object)(_titulo));
 //BA.debugLineNum = 65;BA.debugLine="titulolbl.TextColor = Colors.White";
_titulolbl.setTextColor(anywheresoftware.b4a.keywords.Common.Colors.White);
 //BA.debugLineNum = 66;BA.debugLine="titulolbl.TextSize = 20";
_titulolbl.setTextSize((float) (20));
 //BA.debugLineNum = 67;BA.debugLine="contenido.Text = text";
_contenido.setText((Object)(_text));
 //BA.debugLineNum = 68;BA.debugLine="contenido.TextColor = Colors.White";
_contenido.setTextColor(anywheresoftware.b4a.keywords.Common.Colors.White);
 //BA.debugLineNum = 69;BA.debugLine="contenido.TextSize = 22";
_contenido.setTextSize((float) (22));
 //BA.debugLineNum = 70;BA.debugLine="contenido.Gravity = Gravity.CENTER";
_contenido.setGravity(anywheresoftware.b4a.keywords.Common.Gravity.CENTER);
 //BA.debugLineNum = 71;BA.debugLine="contenido.Color = Colors.ARGB(255,73,202,138)";
_contenido.setColor(anywheresoftware.b4a.keywords.Common.Colors.ARGB((int) (255),(int) (73),(int) (202),(int) (138)));
 //BA.debugLineNum = 72;BA.debugLine="panelcontent.Color = Colors.ARGB(255,73,202,138)";
_panelcontent.setColor(anywheresoftware.b4a.keywords.Common.Colors.ARGB((int) (255),(int) (73),(int) (202),(int) (138)));
 //BA.debugLineNum = 73;BA.debugLine="panelcontent.AddView(MsgTopImg, 0, 0,90%x, 60dip)";
_panelcontent.AddView((android.view.View)(_msgtopimg.getObject()),(int) (0),(int) (0),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (90),_ba),anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (60)));
 //BA.debugLineNum = 74;BA.debugLine="panelcontent.AddView(titulolbl, 5%x, 0, 90%x, 60d";
_panelcontent.AddView((android.view.View)(_titulolbl.getObject()),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (5),_ba),(int) (0),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (90),_ba),anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (60)));
 //BA.debugLineNum = 75;BA.debugLine="panelcontent.AddView(contenido, 5%x, 60dip, 80%x,";
_panelcontent.AddView((android.view.View)(_contenido.getObject()),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (5),_ba),anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (60)),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (80),_ba),anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (160)));
 //BA.debugLineNum = 76;BA.debugLine="panelcontent.AddView(MsgBottomImg, 0, 280dip, 90%";
_panelcontent.AddView((android.view.View)(_msgbottomimg.getObject()),(int) (0),anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (280)),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (90),_ba),anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (60)));
 //BA.debugLineNum = 78;BA.debugLine="msg = dial.CustomDialog(\"\", 90%x, 60dip, panelcon";
_msg = BA.NumberToString(_dial.CustomDialog((Object)(""),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (90),_ba),anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (60)),(anywheresoftware.b4a.objects.ConcreteViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.ConcreteViewWrapper(), (android.view.View)(_panelcontent.getObject())),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (90),_ba),anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (340)),anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (5),_ba),anywheresoftware.b4a.keywords.Common.Null,(Object)(_botontextoyes),(Object)(_botontextocan),(Object)(_botontextono),anywheresoftware.b4a.keywords.Common.False,"",_ba));
 //BA.debugLineNum = 79;BA.debugLine="Return msg";
if (true) return _msg;
 //BA.debugLineNum = 80;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 7;BA.debugLine="End Sub";
return "";
}
public static String  _sabiasque(anywheresoftware.b4a.BA _ba) throws Exception{
String _titulo = "";
String _textoboton = "";
int _random = 0;
anywheresoftware.b4a.objects.collections.List _sqpalabras = null;
int _rndsize = 0;
String _wordx = "";
 //BA.debugLineNum = 15;BA.debugLine="Sub SabiasQue";
 //BA.debugLineNum = 16;BA.debugLine="Dim titulo As String";
_titulo = "";
 //BA.debugLineNum = 17;BA.debugLine="Dim textoboton As String";
_textoboton = "";
 //BA.debugLineNum = 18;BA.debugLine="Dim random As Int";
_random = 0;
 //BA.debugLineNum = 19;BA.debugLine="Dim SQPalabras As List";
_sqpalabras = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 22;BA.debugLine="If Main.lang = \"en\" Then";
if ((mostCurrent._main._lang).equals("en")) { 
 //BA.debugLineNum = 23;BA.debugLine="titulo = \"Did you know?\"";
_titulo = "Did you know?";
 //BA.debugLineNum = 24;BA.debugLine="textoboton = \"Great!\"";
_textoboton = "Great!";
 //BA.debugLineNum = 25;BA.debugLine="SQPalabras = File.ReadList(File.DirAssets, \"en-S";
_sqpalabras = anywheresoftware.b4a.keywords.Common.File.ReadList(anywheresoftware.b4a.keywords.Common.File.getDirAssets(),"en-SQPalabras.txt");
 }else {
 //BA.debugLineNum = 27;BA.debugLine="titulo = \"¿Sabías?\"";
_titulo = "¿Sabías?";
 //BA.debugLineNum = 28;BA.debugLine="textoboton = \"Buenísimo!\"";
_textoboton = "Buenísimo!";
 //BA.debugLineNum = 29;BA.debugLine="SQPalabras = File.ReadList(File.DirAssets, \"SQPa";
_sqpalabras = anywheresoftware.b4a.keywords.Common.File.ReadList(anywheresoftware.b4a.keywords.Common.File.getDirAssets(),"SQPalabras.txt");
 };
 //BA.debugLineNum = 35;BA.debugLine="Dim rndSize As Int";
_rndsize = 0;
 //BA.debugLineNum = 36;BA.debugLine="rndSize = SQPalabras.Size";
_rndsize = _sqpalabras.getSize();
 //BA.debugLineNum = 37;BA.debugLine="random = Rnd(1,rndSize)";
_random = anywheresoftware.b4a.keywords.Common.Rnd((int) (1),_rndsize);
 //BA.debugLineNum = 38;BA.debugLine="Dim wordx As String";
_wordx = "";
 //BA.debugLineNum = 39;BA.debugLine="wordx = SQPalabras.Get(random)";
_wordx = BA.ObjectToString(_sqpalabras.Get(_random));
 //BA.debugLineNum = 41;BA.debugLine="Mensaje(titulo, wordx, textoboton, \"\", \"\")";
_mensaje(_ba,_titulo,_wordx,_textoboton,"","");
 //BA.debugLineNum = 42;BA.debugLine="End Sub";
return "";
}
}
